// Generated by CoffeeScript 1.10.0
(function() {
  var Adaptly;

  Adaptly = (function() {
    var button, calc, input1, input2, res;

    button = document.getElementById('calc');

    input1 = document.getElementById('input1');

    input2 = document.getElementById('input2');

    res = document.getElementById('res');

    function Adaptly() {
      button.addEventListener('click', calc);
    }

    calc = function() {
      var results, temp;
      temp = true;
      results = input1.value.concat(input2.value);
      temp = /[a{2,}]/.test(results) && temp;
      temp = /d/.test(results) && temp;
      temp = /p/.test(results) && temp;
      temp = /t/.test(results) && temp;
      temp = /l/.test(results) && temp;
      temp = /y/.test(results) && temp;
      return res.innerHTML = temp;
    };

    Adaptly.prototype.printInput1 = function() {
      return document.getElementById('input1').value;
    };

    return Adaptly;

  })();

  new Adaptly();

}).call(this);
