// Generated by CoffeeScript 1.10.0
(function() {
  var test;

  test = function(str1, str2) {
    var results, temp;
    temp = true;
    results = str1.concat(str2);
    temp = /[a{2,}]/.test(results) && temp;
    temp = /d/.test(results) && temp;
    temp = /p/.test(results) && temp;
    temp = /t/.test(results) && temp;
    temp = /l/.test(results) && temp;
    temp = /y/.test(results) && temp;
    return temp;
  };

  describe('Adaptly', function() {
    it('ad' + 'aptlyd', function() {
      return expect(test('ad', 'aptlyd')).toBe(true);
    });
    it('aasdd' + 'aptlyd', function() {
      return expect(test('aasdd', 'aptlyd')).toBe(true);
    });
    it('a' + 'd', function() {
      return expect(test('a', 'd')).toBe(false);
    });
    it('mark' + 'acosta', function() {
      return expect(test('mark', 'acosta')).toBe(false);
    });
    return it('li' + 'adapt', function() {
      return expect(test('li', 'adapt')).toBe(false);
    });
  });

}).call(this);
